# :::::::::::::::::::
# Default section
# :::::::::::::::::::
default:

# :::::::::::::::::::
# DATABASE SETTINGS, RDF4J
# :::::::::::::::::::
  ADMIN_USER: 'username'
  ADMIN_PASS: 'password'

  EDITOR_USER: 'username'
  EDITOR_PASS: 'password'

  VIEWER_USER: 'username'
  VIEWER_PASS: 'password'

# :::::::::::::::::::
# Plone Settings, User
# :::::::::::::::::::

  HARVEST_USER: 'XXX'
  HARVEST_PASS: 'XXX'

# :::::::::::::::::::
# Mail Settings, sending Problem Mails
# :::::::::::::::::::

  MAIL_USERNAME: 'username'
  MAIL_PASSWORD: 'pw'
  MAIL_PORT: 25
  MAIL_SERVER: 'server'